import { InferType, number, object, string } from "yup";

export const addPhotoSchema = object({
  title: string().required("Title is required"),
  url: string().required("URL is required").url("URL must be a valid URL"),
  id: number().optional(), // This will be autogenerated
  // albumId is not included in the schema as it's not provided by the user
});

export type PhotoDto = InferType<typeof addPhotoSchema>;
